### PR TITLE
prompt: set the parent of the dialog

### LINKED ISSUE #75: Password prompt is not a dialog
I looked at the code and it looks fine, but `xprop` tells me it is not getting the dialog properties:

```
_NET_WM_USER_TIME(CARDINAL) = 524565221
_NET_WM_STATE(ATOM) = 
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                Initial state is Normal State.
                window id # of group leader: 0x2000001
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 0, 0, 718, 883
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 33554437, 33554438
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x2000004
WM_CLIENT_LEADER(WINDOW): window id # 0x2000001
_NET_WM_PID(CARDINAL) = 29565
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "bronto-burt"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified location: 0, 0
                program specified minimum size: 207 by 105
                program specified base size: 0 by 0
                window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "udiskie-mount", "Udiskie-mount"
WM_ICON_NAME(STRING) = "udiskie"
_NET_WM_ICON_NAME(UTF8_STRING) = "udiskie"
WM_NAME(STRING) = "udiskie"
_NET_WM_NAME(UTF8_STRING) = "udiskie"
```

### PR DESCRIPTION
**Pull request by mathstuf**
Fixes #75.

### CODE REVIEW

**Comment by coldfix** [comment]
Hey,

I'm on awesome (another tiling window manager) this match makes the dummy window briefly appear and then disappear again - which causes annoying flickering.

Can you try the following instead:

```python
def _set_transient(dialog):
    root = Gdk.get_default_root_window()
    dialog.realize()
    dialog.get_window().set_transient_for(root)
```

Since the current udiskie master works perfectly with awesome (is shown as floating dialog, as expected), it might also be worth considering to patch the code in Xmonad instead.

**Comment by mathstuf** [comment]
Ok, so the problem is with my config (likely; haven't tested my fix yet); I was only explicitly floating `Xmessage` and `Xdialog` windows instead of any dialog (which makes me wonder where I'm looking at `WM_TRANSIENT_FOR` to have `zenity` dialogs float properly…). However, GTK is still warning that not setting a transient parent isn't a good idea; not sure of the best way to fix that (`zenity`'s approach is certainly way too complicated for what it is).

The `get_default_root_window` call doesn't work because it isn't a `GtkWindow`, but a `GdkWindow` which is little more than some geometry points in screen-space.

**Comment by coldfix** [comment]
Look more closely at my suggestion: It uses `dialog.get_window()` to get a `Gdk.Window`, which can then be used to set another `Gdk.Window` as the transient one. I tested this one and it doesn't break on awesome, so at least that should be no harm, and maybe it fixes your problem on Xmonad.

However, it will still show the info message regarding the transient window, but I wouldn't worry about that too much. It says only "discouraged" not "deprecated".

(on that matter, there is a bunch of deprecation warnings which I will eventually have to get around fixing)

**Comment by mathstuf** [comment]
OK, so fixing XMonad to float dialogs helps.

**Pull request closed without merging**
