### PR TITLE
Support also new AyatanaAppIndicator3

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
This should fix Debian issue in loading tray, see:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=992080

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
Hello, I didn't test this, does it make any sense? Import AyatanaAppIndicator3 works in Debian now

**Comment by coldfix** [comment]
thanks! I will try to check whether it works.

**Comment by coldfix** [comment]
Finally managed to follow up on this. Thanks again.

**Comment by LocutusOfBorg** [comment]
thanks for merging!

**Pull request merged**
