### PR TITLE
fix failure to start due to module keyutils collision

### PR DESCRIPTION
**Pull request by bubbleguuum**

### CODE REVIEW

**Comment by coldfix** [comment]
Hi,
thanks for the contribution. After a brief check, it seems to me that this isn't the right long term solution. python-keyutils has been archived in 2022, so depending on it is no longer a good option. On the other hand, the python-keyring-keyutils package seems to provide similar functionality as python-keyutils did. I'd prefer to add support for this newer package instead.
Let me see if I find some time to do it right in the near future, otherwise I'll merge this as a temporary hotfix.
Best, Thomas

**Comment by bubbleguuum** [comment]
Agreed this is more band-aid than proper fix. I did it as quick work-around to have the openSUSE udiskie package not crashing.

**Comment by coldfix** [comment]
Hey,
thanks again. I resolved it for now by turning the `AttributeError` into an `ImportError` in cc312f7781ee4f6199ffd071bbe151420b8e63f3. Will be added in next release.
Sorry for the wait.

**Comment by bubbleguuum** [comment]
Thanks for the workaround fix.

**Pull request closed without merging**
